[package]
name = "agent-kernel"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
agent-protocol.workspace = true
aes-gcm.workspace = true
async-trait.workspace = true
futures.workspace = true
hex.workspace = true
provider-core.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
