[package]
name = "provider-openai"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
agent-protocol.workspace = true
async-trait.workspace = true
bytes.workspace = true
futures.workspace = true
hex.workspace = true
provider-core.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
